networks:
    localhost:
        driver: bridge
    production:
        name: ${NGINX_NETWORK_NAME}
        external: true

services:
    titles:
        build: .
        restart: on-failure
        networks:
            - localhost
        ports:
            - 3000:3000 #:3000 # local dev
        env_file:
            - .env
        environment:
            - LETSENCRYPT_HOST=banners.karel-kroeze.nl,headers.karel-kroeze.nl
            - LETSENCRYPT_EMAIL=karel.kroeze@gmail.com
            - VIRTUAL_HOST=banners.karel-kroeze.nl,headers.karel-kroeze.nl
            - VIRTUAL_PORT=3000
        volumes:
            - ./cache:/tmp/cache
            - ./lib:/app/lib
