version: "2"

networks:
  personal:
    # driver: bridge
    external:
      name: srv_personal

services:
  banners:
    build: .
    restart: on-failure
    networks:
      - personal
    ports:
      - 3000 #:3000 # local dev
    env_file:
      - .env
    environment:
      - LETSENCRYPT_HOST=banners.karel-kroeze.nl
      - LETSENCRYPT_EMAIL=karel.kroeze@gmail.com
      - VIRTUAL_HOST=banners.karel-kroeze.nl
      - VIRTUAL_PORT=3000
    volumes:
      - ./cache:/tmp/cache
